version: '3.8'

services:
  postgres_nlw:
    image: postgres
    container_name: postgres_nlw
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: pg_nlw
    ports:
      - "5434:5432"